name: Test PHP 7.x

on:
  push:
    paths-ignore:
      - 'readme.md'
  pull_request:
    paths-ignore:
      - 'readme.md'
  release:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        laravel: [5.1.*, 5.2.*, 5.3.*, 5.4.*, 5.5.*, 5.6.*, 5.7.*, 5.8.*, 6.*, 7.*, 8.*, 10.*]
        php: [7.2, 7.3, 7.4, 8.1]
        exclude:
          - laravel: 10.*
            php: 7.2
          - laravel: 10.*
            php: 7.3
          - laravel: 10.*
            php: 7.4
          - laravel: 8.*
            php: 7.2
      fail-fast: false

    name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extension: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick

      - name: Install dependencies
        run: |
            composer require "illuminate/contracts:${{ matrix.laravel }}" "illuminate/filesystem:${{ matrix.laravel }}" "illuminate/container:${{ matrix.laravel }}" --no-interaction --no-update
            composer update --prefer-stable --prefer-dist --no-interaction --no-suggest

      - name: Run tests
        run: vendor/bin/phpunit
